export const RouteNames = {
    DASHBOARD: "dashboard",
    PROJECT: "project",
    MESSAGE: "message",
    CLIENT: "client",
    TEAMS: "teams",
    MEETINGS: "meetings",
    REFERRALS: "referrals",
    SERVICES: "services",
    CONTRACTS: "contracts",
    INVOICES: "invoices",
    FORMS: "forms",
    FINANCES: "finances",
    ADDPROJECTS: "addproject",
    LOGIN: "login",
    SIGNUP: "signup",
    HOME: "home",
    SINGLEVIDEO: "child-video",
  
    // SUPER ADMIN CONSTANTS
    ADMINLAYOUT: "adminlayout",
    PAYMENT: "payment",
    SUBSCRIPTION: "subscription",
    PLANS: "plans",
    SETTINGS: "settings",
    NOTIFICATIONS: "notifications",
    USERS: "users",
    SUPERDASHBOARD: "admindashboard",
    ADDPLANS: "addplans",
    ADDSUBSCRIPTION: "addsubscription",
  };