export const RouteNames = {
    DASHBOARD: 'dashboard',
    PROJECT: 'project',
    MESSAGE: 'message',
    CLIENT: 'client',
    TEAMS: 'teams',
    MEETINGS: 'meetings',
    REFERRALS: 'referrals',
    SERVICES: 'services',
    CONTRACTS: 'contracts',
    INVOICES: 'invoices',
    FORMS: 'forms',
    FINANCES: 'finances',
    ADDPRODUCTS: 'addproduct',
};